/* 
 * Keyword Extraction
 *
 * The Keyword Extraction API allows you to extract keywords from text. Keywords can be extracted from text, file or stream location. With each extracted keyword a weight will be given.    The flow is generally as follows:  1. Create an extraction job. If no settings are provided, default settings are used.  2. Upload content for extraction.  3. Start the extraction job.  3. Get the result when the extraction is completed.    Full API Documentation: https://docs.sphereon.com/api/extraction/keyword/0.0/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.0
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Extraction.Keyword.Api;
using Sphereon.SDK.Extraction.Keyword.Model;
using Sphereon.SDK.Extraction.Keyword.Client;
using System.Reflection;

namespace Sphereon.SDK.Extraction.Keyword.Test
{
    /// <summary>
    ///  Class for testing Keyword
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KeywordTests
    {
        // TODO uncomment below to declare an instance variable for Keyword
        //private Keyword instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Keyword
            //instance = new Keyword();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Keyword
        /// </summary>
        [Test]
        public void KeywordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Keyword
            //Assert.IsInstanceOfType<Keyword> (instance, "variable 'instance' is a Keyword");
        }

        /// <summary>
        /// Test the property 'InverseDocumentFrequency'
        /// </summary>
        [Test]
        public void InverseDocumentFrequencyTest()
        {
            // TODO unit test for the property 'InverseDocumentFrequency'
        }
        /// <summary>
        /// Test the property 'TermCount'
        /// </summary>
        [Test]
        public void TermCountTest()
        {
            // TODO unit test for the property 'TermCount'
        }
        /// <summary>
        /// Test the property 'TermFrequency'
        /// </summary>
        [Test]
        public void TermFrequencyTest()
        {
            // TODO unit test for the property 'TermFrequency'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property '_Keyword'
        /// </summary>
        [Test]
        public void _KeywordTest()
        {
            // TODO unit test for the property '_Keyword'
        }
        /// <summary>
        /// Test the property 'NormalizedWeight'
        /// </summary>
        [Test]
        public void NormalizedWeightTest()
        {
            // TODO unit test for the property 'NormalizedWeight'
        }

    }

}
